name: Docs build and upload

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup Sphinx
        run: |
          pip install sphinx sphinx_rtd_theme sphinx_gallery
      - name: Sphinx Build
        run: |
          cd 'docs'
          make html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/_build/html"

      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
